[package]
name = "ddc-shob"
version = "0.2.0"
authors = ["ana <ana@altonotch.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3.8", default-features = false}
ssh2 = "0.7.1"
uuid = { version = "0.8", features = ["v4"] }
