[package]
name = "ddc-shob"
version = "0.2.1"
authors = ["Chiliseed <info@chiliseed.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3.11", default-features = false}
ssh2 = "0.8.0"
uuid = { version = "0.8.1", features = ["v4"] }
